version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: acessafacil
      POSTGRES_USER: acessafacil
      POSTGRES_DB: acessafacil
    ports:
      - 5433:5432
    volumes:
      # - db.sql:/docker-entrypoint-initdb.d/
      - /docker/postgres:/var/lib/postgresql/data