version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: acessafacil
      POSTGRES_USER: acessafacil
      POSTGRES_DB: acessa-facil
    ports:
      - 15432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data