##############
# Companys   #
##############
POST http://localhost:3000/companys
Content-Type: application/json

{
    "password": "1234",
    "name": "teste",
    "email": "teste@gmail.com",
    "identity": "78514420030184",
    "identityType": "cnpj",
    "address": {
        "city": "São Paulo",
        "uf": "SP",
        "address": "Rua teste 123",
        "zipCode": "12345000"
    }
}

##############
# Visitors   #
##############

#######
POST http://localhost:3000/visitors
Content-Type: application/json

{
    "password": "teste",
    "fullName": "teste",
    "email": "teste32@gmail.com",
    "birthday": "2002-12-07T02:00:00.000Z",
    "identity": "78554420000184",
    "identityType": "cnpj",
    "address": "{\"city\":\"São Paulo\",\"uf\":\"SP\",\"address\":\"Rua teste 123\",\"zipCode\":\"12345000\"}",
    "file": "data, image"
}
##############
#   VISITS   #
##############

##############
POST http://localhost:3000/visits
Content-Type: application/json

{
    "visitorId": "bbb0b44c-9c00-4a30-9186-87e0a9449dc8",
    "companyId": "9b86dc39-84c6-48f0-b48a-abec0a047f4b",
    "scheduledDate": "2024-04-20T17:59:59.563Z"
}

##############
GET http://localhost:3000/visits/companys/dd303319-02e5-4349-bf4b-aa773d2718b7
Content-Type: application/json

##############
GET http://localhost:3000/visits/dd303319-02e5-4349-bf4b-aa773d2718b7
Content-Type: application/json
##############
PATCH http://localhost:3000/visits/bbb0b44c-9c00-4a30-9186-87e0a9449dc8
Content-Type: application/json

{
    "approved": true
}
##############
PATCH http://localhost:3000/visits/bbb0b44c-9c00-4a30-9186-87e0a9449dc8
Content-Type: application/json

{
    "approved": false,
}
##############

PATCH http://localhost:3000/visits/bbb0b44c-9c00-4a30-9186-87e0a9449dc8
Content-Type: application/json

{
    "finished": true
}

##############
#    AUTH    #
##############

##############
POST http://localhost:3000/auth/companys
Content-Type: application/json

{
    "password": "123456",
    "email": "info@tesla.com"
}
##############
POST http://localhost:3000/auth/visitors
Content-Type: application/json

{
    "password": "teste",
    "email": "teste32@gmail.com"
}
